version: 2.1
workflows:
  main:
    jobs:
         - release
jobs:
  release:
          
    docker:
      - image: docker.io/circleci/golang:1.16.6
      - image: cimg/base:stable
    steps:
      - checkout
      - setup_remote_docker:
          version: 20.10.6
      - run:
          name: Install Docker Buildx
          command: |
            mkdir -vp ~/.docker/cli-plugins/
            curl --silent -L --output ~/.docker/cli-plugins/docker-buildx https://github.com/docker/buildx/releases/download/v0.3.1/buildx-v0.3.1.linux-amd64
            chmod a+x ~/.docker/cli-plugins/docker-buildx
            docker run -it --rm --privileged tonistiigi/binfmt --install all
            docker buildx version
            
      - run:
          name: Prepare env
          command: |
            echo Avinash@8794 | docker login -u avinashyadavpuresoftware --password-stdin
      - run: 
          name: Go releaser
          no_output_timeout: 50m
          command: curl -sL https://git.io/goreleaser | bash
